[package]
name = "edgesearch"
version = "0.0.1"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
bytes = "0.5.4"
byteorder = "1.3.2"
croaring = "0.4.4"
reqwest = "0.10.1"
structopt = "0.3.5"
